export const permissionKeys = [
  "restaurant.view",
  "restaurant.edit",
  "branches.view",
  "branches.manage",
  "features.manage",
  "employees.view",
  "employees.manage",
  "employees.manage_permissions",
  "menu.view",
  "menu.manage",
  "menu.manage_prices",
  "menu.manage_availability",
  "qr.manage",
  "tables.view",
  "tables.manage",
  "tables.assign",
  "tables.close_session",
  "orders.view",
  "orders.create",
  "orders.accept",
  "orders.reject",
  "orders.modify",
  "orders.cancel",
  "orders.serve",
  "orders.complete",
  "orders.complete_unpaid",
  "kitchen.view",
  "kitchen.update",
  "payments.view",
  "payments.record",
  "payments.refund",
  "reports.view",
  "reports.view_cross_branch",
  "audit.view",
  "support.break_glass",
] as const;

export type PermissionKey = (typeof permissionKeys)[number];

export const administratorPermissionKeys = [
  "restaurant.view",
  "restaurant.edit",
  "branches.view",
  "branches.manage",
  "features.manage",
  "employees.view",
  "employees.manage",
  "employees.manage_permissions",
  "menu.view",
  "menu.manage",
  "menu.manage_prices",
  "menu.manage_availability",
  "qr.manage",
  "tables.view",
  "tables.manage",
  "tables.assign",
  "tables.close_session",
  "orders.view",
  "orders.create",
  "orders.accept",
  "orders.reject",
  "orders.modify",
  "orders.cancel",
  "orders.serve",
  "orders.complete",
  "kitchen.view",
  "kitchen.update",
  "payments.view",
  "payments.record",
  "payments.refund",
  "reports.view",
  "reports.view_cross_branch",
  "audit.view",
] as const satisfies readonly PermissionKey[];
