export const copy = {
  brand: "Kanoun",
  brandHomeLabel: "Kanoun home",
  brandMenuTopLabel: "Kanoun menu top",
  menuCategoriesLabel: "Menu categories",
  loadingQrTitle: "Checking this table link",
  loadingQrBody: "Opening the menu for your table.",
  invalidTitle: "This menu link is incomplete",
  invalidBody: "Scan the full QR code at your table and try again.",
  unavailableTitle: "This menu link is no longer available",
  unavailableBody:
    "The code may have been replaced. Ask a member of staff for the current QR code.",
  retry: "Try again",
  tableTitle: "Are you at this table?",
  tableBody: "Check the number printed on your table before you continue.",
  browseTitle: "Browse today’s menu",
  browseBody:
    "You can see every dish here. To order, scan the QR code on your table.",
  nameLabel: "Your name (optional)",
  nameHint: "Helps staff find you. Only used for this visit.",
  namePlaceholder: "How should staff identify you?",
  confirmTable: "Yes, show the menu",
  continueBrowsing: "Show the menu",
  wrongTable: "Not your table? Scan the QR printed where you’re seated.",
  loadingMenuTitle: "Loading the menu",
  loadingMenuBody: "Checking today’s prices and what’s available.",
  menuTitle: "Menu",
  emptyMenuTitle: "The menu is being prepared",
  emptyMenuBody:
    "There are no dishes to show right now. Please ask a member of staff.",
  unavailableDish: "Sold out today",
  addDish: (name: string) => `Add ${name}`,
  addFor: (quantity: number, price: string) =>
    quantity === 1 ? `Add for ${price}` : `Add ${quantity} for ${price}`,
  inOrder: (quantity: number) => `${quantity} in your order`,
  added: (name: string) => `${name} added to your order.`,
  closeDish: "Close",
  hasChoices: "Choose how you’d like it",
  dishCount: (count: number) => (count === 1 ? "1 dish" : `${count} dishes`),
  itemCount: (count: number) => (count === 1 ? "1 dish" : `${count} dishes`),
  decrease: "One fewer",
  increase: "One more",
  sentTitle: "Your order is in",
  sentBody:
    "The kitchen has your ticket. This page follows it until it reaches your table.",
  orderSteps: ["Received", "Preparing", "Ready", "Served"] as const,
  somethingWrong: "Something wrong with this order?",
  optionDetails: "Choices",
  required: "Required",
  optional: "Optional",
  oneChoice: "Choose 1",
  choiceRange: (minimum: number, maximum: number) =>
    `${minimum}–${maximum} choices`,
  browseOnlyNotice: "Menu browsing only. Scan the QR at your table to order.",
  browseOnly: "Browse only",
  tableLabel: "Table",
  menuUpdated: "Up to date",
  reloadMenu: "Reload menu",
  menuLoadErrorTitle: "The menu could not be loaded",
  menuLoadErrorBody: "Check your connection, then reload the current menu.",
  tableVerifiedAnnouncement: "Table link verified.",
  addToOrder: "Add to order",
  quantity: "Quantity",
  noteLabel: "Preparation note (optional)",
  notePlaceholder: "Allergies or preparation requests",
  noteDisclaimer:
    "The kitchen will do its best, but notes can’t change the price and aren’t guaranteed.",
  cartTitle: "Your order",
  cartEmpty: "Choose a dish to begin your order.",
  reviewOrder: "Review order",
  closeReview: "Continue browsing",
  removeItem: "Remove",
  submitOrder: "Send order",
  submittingOrder: "Sending…",
  orderConflict:
    "The menu changed. Reload the current menu, review your choices, and submit again.",
  orderFailure:
    "Your order wasn’t sent. Check your connection and try again. You won’t be charged twice.",
  orderBranchClosed:
    "The restaurant isn’t taking orders right now. Ask a member of staff, or order during opening hours.",
  orderDishUnavailable:
    "Something in your order has just sold out. Reload the menu and check your order.",
  orderTableUnavailable:
    "This table can’t take orders right now. Please ask a member of staff.",
  orderSessionExpired:
    "Your table link has expired. Scan the QR code on your table again.",
  orderRejected:
    "Your order wasn’t accepted. Please ask a member of staff for help.",
  orderReference: "Order reference",
  orderProgress: "Order progress",
  receivedStatus: "Received",
  preparingStatus: "Preparing",
  readyStatus: "Ready for service",
  servedStatus: "Served",
  cancelledStatus: "Cancelled",
  rejectedStatus: "Not accepted",
  addAnotherOrder: "Order more items",
  cancellationTitle: "Request cancellation",
  cancellationReason: "Reason",
  cancellationPlaceholder: "Tell staff what needs to be corrected",
  requestCancellation: "Send request",
  cancellationPending: "Sending…",
  cancellationSent:
    "Cancellation requested. A member of staff will confirm it.",
  cancellationFailure:
    "The cancellation request was not sent. Check your connection and try again.",
  billTitle: "Ready to pay?",
  requestBill: "Request the bill",
  billPending: "Requesting…",
  billSent: "Bill requested. Staff have been notified.",
  billFailure:
    "The bill request was not sent. Check your connection and try again.",
  refreshStatus: "Refresh status",
  refreshingStatus: "Refreshing…",
  statusUpdatesAutomatically:
    "Status updates automatically while this page is open.",
  statusMayBeStale:
    "Status may be out of date. Check your connection, then refresh.",
} as const;
