export const copy = {
  brand: "MISE",
  brandHomeLabel: "MISE home",
  brandMenuTopLabel: "MISE menu top",
  menuCategoriesLabel: "Menu categories",
  menuAccessEyebrow: "Menu access",
  loadingQrEyebrow: "Opening your menu",
  loadingQrTitle: "Checking this table link",
  loadingQrBody: "We’re securely connecting this device to the restaurant.",
  invalidTitle: "This menu link is incomplete",
  invalidBody: "Scan the full QR code at your table and try again.",
  unavailableTitle: "This menu link is no longer available",
  unavailableBody:
    "The code may have been replaced. Ask a member of staff for the current QR code.",
  retry: "Try again",
  tableEyebrow: "Table detected",
  tableTitle: "Are you at this table?",
  tableBody:
    "Check the printed table marker before continuing. Scanning does not occupy the table.",
  browseEyebrow: "Branch menu",
  browseTitle: "Browse today’s menu",
  browseBody:
    "This QR opens the branch menu without selecting a table. You can still view every available dish.",
  nameLabel: "Your name (optional)",
  nameHint: "Saved only on this device for this visit.",
  namePlaceholder: "How should staff identify you?",
  confirmTable: "Yes, show the menu",
  continueBrowsing: "Show the menu",
  wrongTable: "Not your table? Scan the QR printed where you’re seated.",
  loadingMenuEyebrow: "Table confirmed",
  loadingMenuTitle: "Bringing up the current menu",
  loadingMenuBody: "Prices and availability are being checked for this branch.",
  menuEyebrow: "Current branch menu",
  menuTitle: "What’s being served",
  emptyMenuTitle: "The menu is being prepared",
  emptyMenuBody:
    "There are no dishes to show right now. Please ask a member of staff.",
  unavailableDish: "Unavailable today",
  optionDetails: "View choices",
  required: "Required",
  optional: "Optional",
  oneChoice: "Choose 1",
  choiceRange: (minimum: number, maximum: number) =>
    `${minimum}–${maximum} choices`,
  browseOnlyNotice: "Menu browsing only. Ordering is not available here yet.",
  browseOnly: "Browse only",
  tableLabel: "Table",
  menuUpdated: "Live menu",
  reloadMenu: "Reload menu",
  menuUpdateEyebrow: "Menu update",
  menuLoadErrorTitle: "The menu could not be loaded",
  menuLoadErrorBody: "Check your connection, then reload the current menu.",
  tableVerifiedAnnouncement: "Table link verified.",
} as const;
